---
- hosts: [ "node1", "node2", "node3" ]
  sudo: yes
  sudo_user: root
  tasks:
  
  - include: tasks/dependencies.yml
  - include: tasks/repositories.yml
  - include: tasks/java-install.yml
  - include: tasks/dsc-install.yml
  - include: tasks/start-cassandra.yml
