- name: updating yum on host
  shell: yum update -y

- name: installing some dependencies
  yum: pkg={{ item }} state=installed 
  with_items:
  - vim
  - jna
  - sysstat
  - libselinux-python
  - lsof

